workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

image: node:20

before_script:
  - npm install -g @google/gemini-cli

build-job:
  stage: build
  script:
    - echo ${GEMINI_API_KEY}
    - export GITLAB_TOKEN=$(echo $GITLAB_TOKEN)

    - gemini -y -p "review changes in merge request $CI_MERGE_REQUEST_IID in project $CI_PROJECT_ID and add detailed summary, impact of new changes, readiness to merge, test coverage, changes highlights, file by file with filepaths and changes changelog and activity sections with info about who and when opened merge request and branch info, also how many days, hours, minutes merge request was opened in markdown format as a comment"

